// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace VoltagePrediction
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {

            [LoadColumn(0)]
            [ColumnName(@"payload.ECM_MPG")]
            public float Payload_ECM_MPG { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"payload.ECM_EngineTotalIdleFuelUsed")]
            public float Payload_ECM_EngineTotalIdleFuelUsed { get; set; }
            [LoadColumn(2)]
            [ColumnName(@"payload.ECM_EngineTotalIdleHours")]
            public float Payload_ECM_EngineTotalIdleHours { get; set; }
            [LoadColumn(3)]
            [ColumnName(@"payload.ECM_EngineTotalHours")]
            public float Payload_ECM_EngineTotalHours { get; set; }
            [LoadColumn(4)]
            [ColumnName(@"payload.ECM_EngineTotalFuelUsed")]
            public float Payload_ECM_EngineTotalFuelUsed { get; set; }
            [LoadColumn(5)]
            [ColumnName(@"payload.ECM_FuelLevel")]
            public float Payload_ECM_FuelLevel { get; set; }
            [LoadColumn(6)]
            [ColumnName(@"payload.ECM_FuelTeemp")]
            public float Payload_ECM_FuelTeemp { get; set; }
            [LoadColumn(7)]
            [ColumnName(@"payload.SPN917")]
            public float Payload_SPN917 { get; set; }
            [LoadColumn(8)]
            [ColumnName(@"payload.SPN158")]
            public string Payload_SPN158 { get; set; }
            [LoadColumn(9)]
            [ColumnName(@"payload.Ambient_Air_Temperature")]
            public float Payload_Ambient_Air_Temperature { get; set; }
            [LoadColumn(10)]
            [ColumnName(@"payload.Total_Vehicle_Distance_Travelled")]
            public float Payload_Total_Vehicle_Distance_Travelled { get; set; }
            [LoadColumn(11)]
            [ColumnName(@"payload.Parking_Brake_Switch")]
            public string Payload_Parking_Brake_Switch { get; set; }
            [LoadColumn(12)]
            [ColumnName(@"payload.VOL")]
            public float Payload_VOL { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"payload.ECM_MPG")]
            public float Payload_ECM_MPG { get; set; }

            [ColumnName(@"payload.ECM_EngineTotalIdleFuelUsed")]
            public float Payload_ECM_EngineTotalIdleFuelUsed { get; set; }

            [ColumnName(@"payload.ECM_EngineTotalIdleHours")]
            public float Payload_ECM_EngineTotalIdleHours { get; set; }

            [ColumnName(@"payload.ECM_EngineTotalHours")]
            public float Payload_ECM_EngineTotalHours { get; set; }

            [ColumnName(@"payload.ECM_EngineTotalFuelUsed")]
            public float Payload_ECM_EngineTotalFuelUsed { get; set; }

            [ColumnName(@"payload.ECM_FuelLevel")]
            public float Payload_ECM_FuelLevel { get; set; }

            [ColumnName(@"payload.ECM_FuelTeemp")]
            public float Payload_ECM_FuelTeemp { get; set; }

            [ColumnName(@"payload.SPN917")]
            public float Payload_SPN917 { get; set; }

            [ColumnName(@"payload.SPN158")]
            public float[] Payload_SPN158 { get; set; }

            [ColumnName(@"payload.Ambient_Air_Temperature")]
            public float Payload_Ambient_Air_Temperature { get; set; }

            [ColumnName(@"payload.Total_Vehicle_Distance_Travelled")]
            public float Payload_Total_Vehicle_Distance_Travelled { get; set; }

            [ColumnName(@"payload.Parking_Brake_Switch")]
            public float[] Payload_Parking_Brake_Switch { get; set; }

            [ColumnName(@"payload.VOL")]
            public float Payload_VOL { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
